<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIcNnOTx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIcNnOTx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIcNnOTx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIcNnOTx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIcNnOTx\App_KernelDevDebugContainer([
    'container.build_hash' => 'IcNnOTx',
    'container.build_id' => '3d2149ab',
    'container.build_time' => 1693212832,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIcNnOTx');
